#!/bin/bash
while read oldrev newrev ref
do
	if [[ $ref =~ .*/master$ ]];
	then
		echo "Master ref received. Deploying master branch to production..."
		sudo git --work-tree=/project/prod_server --git-dir=/home/appuser/star_predict checkout -f
	else
		echo "Ref $ref successfully received. Doing nothing: only the master branch may be deployed on this server."
	fi
done
