version: "3.4"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    restart: always
    ports:
      - "5100:5100"
    depends_on:
      - rabbit
    volumes:
      - .:/star_predict
  rabbit:
    hostname: rabbit
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  worker_1:
    build:
      context: .
      network: host
    hostname: worker_1
    entrypoint: celery
    command: -A worker worker --loglevel=debug
    volumes:
      - .:/star_predict
    links:
      - rabbit
    depends_on:
      - rabbit
